### ISSUE TITLE
procedure runs error

### ISSUE THREAD

**Issue by Pe4nut7** [sammyfranklin/wow-fishing-bot#2]
@sammyfranklin 

procedure runs error

![procedure runs error](https://user-images.githubusercontent.com/74670954/99555272-17eefb00-29fb-11eb-89c4-936ae44c1f4b.png)

**Comment by rsamf** [comment]
Looks like a problem with your configuration maybe? Try to find where settings.time_before_logout is defined because it looks like that is being reported as an instance of 'NoneType'. I'm not sure because I no longer maintain this repo.

**Comment by Pe4nut7** [comment]
The file downloaded here has not been modified and I don't know how to modify it
![152352](https://user-images.githubusercontent.com/74670954/99673656-0287d880-2ab0-11eb-8002-f7d9d4a9c975.png)

**Comment by rsamf** [comment]
See: https://github.com/sammyfranklin/wow-fishing-bot/blob/master/src/setup.py#L105

Looks like this line takes the settings.time_before_logout from the field "timeInSecsBeforeLogout" in the configuration file, but I don't see this being mentioned in the template configuration file. It should be added @delirius325. 

@Pe4nut7 set "timeInSecsBeforeLogout" in your config/config.json to a valid time, say 30, and try it out. Also, if you want to learn how to modify Python files, find a Python tutorial :). Python has one of the biggest communities.

**Comment by anthonygauthier** [comment]
Indeed, there are no code modifications to be added. All you need to do is add `timeInSecsBeforeLogout` to your config.json file. If you don't have a config.json file yet, just create one with the template that's available in the `config/README.md` file and then add the previously mentioned field at the root of the JSON object.

**Comment by anthonygauthier** [comment]
@Pe4nut7 Also, please note that this is open-source software. Directly emailing a contributor **demanding** for code modifications won't do anything but aggravate that person.

I've contributed to the repo because I was using the software. However, I am not actively maintaining it nor will I ever be (unless I use it again). 

As @sammyfranklin mentioned it before... I, too, cordially invite you to learn a little bit of Python if you want to solve further issues with the bot.

Thanks 😊

**Comment by Pe4nut7** [comment]
Sorry, I really want to use it very sorry

**Comment by anthonygauthier** [comment]
@Pe4nut7 No worries, you might not be familiar with how open-source software works. I was just explaining for future reference 😉

**Comment by Pe4nut7** [comment]
You can upload one config.json Documents? Please. Thank you

**Comment by Pe4nut7** [comment]
Thank you very much

**Comment by anthonygauthier** [comment]
> You can upload one config.json Documents? Please. Thank you

All you have to do is create a file named `config.json` in the `config` folder. The content of that file will be a copy-paste of the quoted content of the `config/README.md` file. All you need to do, is add this after `"attachBait": true`

```json
timeInSecsBeforeLogout: 3600,
```
Your file should look like this:

```json
​{
    ​"​attachBait​"​: ​true​,
    "timeInSecsBeforeLogout": 3600,
    ​"​autoLoot​"​: ​true​,
    ​"​imageDir​"​: ​"​"​,
    ​"​castLocation​"​: {
        ​"​x​"​: ​0​,
        ​"​y​"​: ​0​
    },
    ​"​poleLocation​"​: {
        ​"​x​"​: ​0​,
        ​"​y​"​: ​0​
    },
    ​"​baitLocation​"​: {
        ​"​x​"​: ​0​,
        ​"​y​"​: ​0​
    },
    ​"​areaOfInterest​"​: [
        {
            ​"​x​"​: ​0​,
            ​"​y​"​: ​0​
        },
        {
            ​"​x​"​: ​0​,
            ​"​y​"​: ​0​
        },
        {
            ​"​x​"​: ​0​,
            ​"​y​"​: ​0​
        },
    ],
    ​"​lootLocation​"​: {
        ​"​x​"​: ​0​,
        ​"​y​"​: ​0​
    }
}
```

**Comment by Pe4nut7** [comment]
![1111](https://user-images.githubusercontent.com/74670954/99803420-6247b780-2b74-11eb-86a3-17a6655a1959.png)
Sorry, I didn't run it successfully

**Comment by anthonygauthier** [comment]
Copy paste your config file here please

**Comment by Pe4nut7** [comment]
![1111](https://user-images.githubusercontent.com/74670954/99804058-61635580-2b75-11eb-86fa-2c787b0fabd2.png)
![222](https://user-images.githubusercontent.com/74670954/99804100-704a0800-2b75-11eb-96af-cb063948fb4c.png)

**Comment by anthonygauthier** [comment]
You have to remove lines 1 to 3 completely. That's not part of the JSON file

**Comment by anthonygauthier** [comment]
Line 40 as well

**Comment by Pe4nut7** [comment]
![Uploading 222.png…]()

**Comment by Pe4nut7** [comment]
![1111](https://user-images.githubusercontent.com/74670954/99805657-d041ae00-2b77-11eb-9377-cc9ba7bb9902.png)
![222](https://user-images.githubusercontent.com/74670954/99805677-d768bc00-2b77-11eb-98f3-faed59585d49.png)
![222](https://user-images.githubusercontent.com/74670954/99805674-d6378f00-2b77-11eb-8813-8ec405e83357.png)

**Comment by anthonygauthier** [comment]
Alright, I don't understand why you're being given those errors. There must a misconfiguration somewhere.... 

Anyways please remove the `config.json` file. Then go into the `settings.py` file and change this line (36) :

```python
self.time_before_logout = None
```

to this:

```python
self.time_before_logout = 3600
# 3600 is an hour ... So if you want the bot to run for longer (or shorter), just modify the number value
```

Then run the bot and everything should be OK.

**Comment by Pe4nut7** [comment]
Everything is fine. Thank you very much. You are my God
