### ISSUE TITLE
slow is_splash_whitepx()

### ISSUE THREAD

**Issue by hirnwunde** [sammyfranklin/wow-fishing-bot#5]
Have played a bit with your code and found that the function `is_splash_whitepx()` was a bit slow.
Here my much faster function with same results:

```python
def is_splash_whitepx(threshold, current):
    white_pixels = (current >= 245).sum()
    if white_pixels> threshold:
        print(f'>>> {white_pixels}')
        return True
    print(f'<<< {white_pixels}')
    return False
```
Sorry ... I don't use git very often and I am too incapable to apply for a PR

**Comment by rsamf** [comment]
There may be many inefficiencies throughout the code. Feel free to fork the repo and work on your own version.
